[package]
name = "sctgdesk-api-server"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "libs/utils",
    "libs/state",
    "libs/oauth2"
]

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["full"] }
bcrypt = "0.13"
rocket = { version = "0.5", features = ["json", "tls", "secrets"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-rustls", "macros", "chrono", "json"] }
reqwest = { version = "0.12", features = ["json"] }
rocket_okapi = { version = "0.8", features = [ "rapidoc" ]}
serde = { version = "1.0", features = ["derive"] }
state = { path = "libs/state" }
utils = { path = "libs/utils" }
oauth2 = { path = "libs/oauth2" }
uuid = { version = "1.0", features = ["v4"] }
base64 = "0.22"
url = { version = "2.3", features = ["serde"] }
urlencoding = "2.1"
serde_json = "1.0"